### ISSUE TITLE
Create a PR for this branch on ocaml/ocaml

### ISSUE THREAD

**Issue by bluddy** [ocamllabs/ocaml-multicore#5]
KC wrote a blog post [here](http://kcsrk.info/multicore/opam/ocaml/2015/03/25/opam-switch-to-multicore/) about how to create an opam switch from a local compiler installation, but truthfully it would be much easier to just submit a PR to the ocaml github mirror. OPAM would then have an easy switch for the branch, just as pr132 tracks the Flambda branch.

I didn't want to go ahead and do it myself, though it would only take a minute -- would one of the contributors to this branch want to do it instead?

**Comment by yallop** [comment]
The workflow that KC's post describes is useful for working on the compiler.  If you're just looking to try out a branch, it's probably easier to set up a local OPAM repository with a compiler description along these lines:

   https://github.com/ocamllabs/opam-repo-dev/blob/master/compilers/4.02.1%2Bmulticore.comp

**Comment by bluddy** [comment]
I don't know that this is easier. I mean, all it takes is one PR on the ocaml repository and everybody is one command away from trying it out. Are you opposed to people trying out the branch? It seemed from KC's post, and the new post today on Algebraic Effects (which is very neat btw) that he was interested in people trying out the branch.

**Comment by lpw25** [comment]
PR are not there to make it easier for people to try things out they are there to make it easier for developers and the community to review the code. The fambda branch is currently undergoing such review which is why it has an associated PR. The multicore branch is not yet in a state to be reviewed and so should not have a PR.

For trying the branch out (and other branches from OCaml Labs), there is the OCaml Labs dev repo:

    https://github.com/ocamllabs/opam-repo-dev

which is easy to add to your opam remotes list.

**Comment by bluddy** [comment]
Fair enough, point accepted. Thanks for the link.

**Comment by kayceesrk** [comment]
Thanks @yallop @lpw25 for the link, and @bluddy for bring this up. I've updated the post with the new link.
