### ISSUE TITLE
weak-ephe-final issue468 can fail with really small minor heaps

### ISSUE THREAD

**Issue by sadiqj** [ocamllabs/ocaml-multicore#526]
Running just the weak-ephe-final tests with a small minor heap (4096 words) will sometimes cause the issue468 test to fail:

`OCAMLRUNPARAM=s=4096,v=0 USE_RUNTIME=d make -C testsuite one DIR=tests/weak-ephe-final`

The failure is:

```
> ### begin stdout ###
> [01] file major_gc.c; line 153 ### Assertion failed: caml_gc_phase == Phase_sweep_and_mark_main
> ### end stdout ###
```

**Comment by Sudha247** [comment]
I had a go at this, what I see during this failure is:
* Orphaned structure is empty. At this point, the major GC goes to `try_complete_gc_phase`. All necessary conditions are met here, so the GC phase is changed from `Phase_sweep_and_mark_main` to `Phase_mark_final`.

* `num_domains_to_final_update_first` is not `0`, so major GC remains in the same phase.

* Now, one of the domains is going to terminate and it is trying to handover finalizers to orphaned list. The assertion that GC is in phase `Phase_sweep_and_mark_main` fails when trying to add finalizers of that domain to orphaned list, because the GC is in `Phase_mark_final` .

A question I had on this is, why is it not valid for finalizer orphaning to take place during `Phase_mark_final`?  In this particular test case at least, I'm assuming one of the live domains would adopt orphaned work later, after the terminating domain's finalizers are added to orphaned list.
