### ISSUE TITLE
`Alloc_small` not robust to GC function leaving not enough space in minor heap

### ISSUE THREAD

**Issue by ctk21** [ocamllabs/ocaml-multicore#538]
We have an issue with our `Alloc_small` macro where it does not correctly handle the case when the `GC` function does not return a minor heap with enough size for the allocation. 

This can happen in cases where a finaliser or signal handler run after the minor collection but then fill up the minor heap.

**Comment by abbysmal** [comment]
My line of thinking would be to change this line https://github.com/ocaml-multicore/ocaml-multicore/blob/4.12%2Bdomains%2Beffects/runtime/caml/memory.h#L225

Instead of a single `if` check, we could turn it into a loop:
```c
while (Caml_check_gc_interrupt(dom_st)) {
```
the `Caml_check_gc_interrupt` checks that the minor heap is usable at the moment:
```c
#define Caml_check_gc_interrupt(dom_st)   \                                                                                                                                                                                                   
  (CAMLalloc_point_here, \                                                                                                                                                                                                                    
   CAMLunlikely((uintnat)(dom_st)->young_ptr < (dom_st)->young_limit)) 
```
If the handler filled it beforehand this check would fail properly.

However this does not account for various DLABs scenarios (misconfiguration of a segment size, where an allocation would never fit in a small enough minor heap segment).
It does account for DLABs failing to replenish after a minor collection , though. (since it fails the `Caml_check_gc_interrupt` if the `young_*` fields are set to proper defaults)
(DLABs is however a separate concern, I think this solution  would work well enough for the current branch.)
