### ISSUE TITLE
Strange memory leak when using `flush_all`

### ISSUE THREAD

**Issue by jO-Osko** [ocamllabs/ocaml-multicore#627]
Using `flush_all` with `ocamlc` on a fresh version of multicore produces a strange memory leak.

The problematic code

```
let printer num 
    =
  print_int num;
  flush_all ()

let lst = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18; 19; 20]

let _ = List.iter printer (lst @ lst @ lst @ lst)
```

On my computer (macos), this produces just `12345678910111213` and then crashes (the memory consumption increases rapidly just before the crash at approx 0.3 Gb per second), running the same inside docker gets it killed due to lack of memory and produces the same output. 

Removing `flush_all` makes the problem go away. 

Strangely, this only happens with `ocamlc` eg running`ocamlc a.ml && ./a.out`, running `ocaml a.ml` produces desired output.

Multicore ocaml was installed through opam `opam switch create 4.12.0+domains --repositories=multicore=git+https://github.com/ocaml-multicore/multicore-opam.git,default`.

Reported version:
```
The OCaml runtime, version 4.12.0+domains+effects
Built with git hash '6c8abc7ab4' on branch 'master' with tag '<tag unavailable>'
```

**Comment by abbysmal** [comment]
Hello,

Thank you very much for reporting!
I looked into it briefly, it seems this was introduced in 43501299f0c997d4ab1fc557c1745d2f2b9055bb

More specifically [this line in unlink_channel](https://github.com/ocaml-multicore/ocaml-multicore/blob/4.12%2Bdomains%2Beffects/runtime/io.c#L98) seems to be able to transform the list into a cycle.
```c
// before cycle is created
(rr) p caml_all_opened_channels
$143 = (struct channel *) 0x55cd5742d9c0
(rr) p caml_all_opened_channels->next
$144 = (struct channel *) 0x55cd5743da50
(rr) p caml_all_opened_channels->next->next
$145 = (struct channel *) 0x55cd5741d930
(rr) p caml_all_opened_channels->next->next->next
$146 = (struct channel *) 0x0
// io.c:98 will set channel->prev->next to channel->next, which is the cause of the cycle
(rr) p channel->prev
$148 = (struct channel *) 0x55cd5743da50
// however channel->next is also the same value
(rr) p channel->next
$164 = (struct channel *) 0x55cd5743da50
// so when it sets channel->prev->next to channel->next it will create a cycle.
```

My intuition is that there may be a small oversight in the `link_channel` code rather than the `unlink_channel` one.
I will look into a fix on monday if @kayceesrk doesn't find it before.

Thanks again for reporting!
