### ISSUE TITLE
ephemerons: audit that we don't have the bug fixed in ocaml#9424

### ISSUE THREAD

**Issue by ctk21** [ocamllabs/ocaml-multicore#667]
During the rebase to ocaml/trunk it wasn't immediately obvious to me if the ocaml-multicore implementation of ephemerons needs to take account of the bug fixed in [ocaml#9424](https://github.com/ocaml/ocaml/pull/9424).

Are there any changes we should consider on the ocaml-multicore side?

**Comment by kayceesrk** [comment]
The bug is very hard to reproduce from the original bug report. But the test included in the PR does not fail on multicore (which is reported to fail consistently on trunk before the fix). Multicore reimplements ephemerons using different data structures. So the fix in the PR doesn't directly apply. I believe that the bug and fix are not applicable to multicore.
