### ISSUE TITLE
caml_process_pending_actions_exn is missing

### ISSUE THREAD

**Issue by sadiqj** [ocamllabs/ocaml-multicore#791]
The `caml_process_pending_actions_exn` C API call is missing on multicore. This returns exceptions as an OCaml value rather than raising them. I can't see any technical limitations to re-adding this but it is going to be tricky to do so and require a reorganisation of the GC and STW logic.

Related to https://github.com/ocaml-multicore/ocaml-multicore/pull/790

**Comment by gadmm** [comment]
For the context, the bigger picture is that there was a lot of resource unsafety in the runtime due to asynchronous exceptions being raised (and there still is, with PRs open to progress in fixing the situation). This function is part of an effort to 1) reduce the number of places where such exceptions can arise and 2) provide ways to properly deal with them (clean-up resources and re-raise). The rationalization of async exceptions in the runtime was started by Jacques-Henri for the purpose of memprof to avoid it remaining in an invalid state when exceptions arise during allocations, so it happened in parallel of the multicore development. So any reorganisation is normal (and typical of this effort) because the code has to be async-exception-safe.

This particular function was introduced for Coq but it was also used to fix bugs in the ocaml runtime (see e.g. `runtime/gc_ctrl.c`), so I wonder what happened to the calls to this function (and their associated commits) during the rebase on top of 4.12.

**Comment by gadmm** [comment]
This is now fixed in the PR mentioned above, the issue can be closed.
